### ISSUE TITLE
Nedostaje eVehicleRegistrationAPI.dll u lib folderu

### ISSUE THREAD

**Issue by neman** [clearpath/Saobracajna.NET#1]
Vidim da je u Sample projektu dodato `<Content Include="..\..\lib\eVehicleRegistrationAPI.dll">` ali taj fajl nedostaje. Da li je to sa namerom ili slučajno?

Ja sam ga ručno dodao mom clone repository-ju.

**Comment by clearpath** [comment]
Kriv je gitignore.

Hvala na dojavi :)
